name: Parse new databse entry issue
on:
  issues:
    types: opened
concurrency: 'main'
jobs:
  place_order:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: stefanbuck/github-issue-praser@v2
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/new_database_entry.yml

      - run: echo '${{ steps.issue-parser.outputs.jsonString }}' > order.json

      - run: cat order.json


        run: |
          python 
      - name: Rename and convert file to YAML
        run: |
          output=$(python ./src/auto_json_to_database_yaml.py)
          echo "::set-output name=changelog::$output"
        id: step1
      - name: Print changelog
        run: echo "${{ steps.step1.outputs.changelog }}"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          add-paths: |
            ${{ steps.step1.outputs.changelog }}
          commit-message: Auto PR
          title: Update Changelog
          body: Update changelog to reflect release changes
          branch: update-changelog
          base: main
