name: parse-issue

on:
  issues:
    types: [opened]

defaults:
  run:
    shell: pwsh
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
     - name: Checkout repository
       uses: actions/checkout@v3
     - uses: edumserrano/github-issue-forms-parser@v1
       id: issue-parser
       with:
        template-filepath: .github/ISSUE_TEMPLATE/new_database_entry.yml
        issue-form-body:  ${{ needs.workflow-args.outputs.issue-body }}
     - name: Show parsed data JSON
       run: |
        Write-Host "${{ steps.issue-parser.outputs.jsonString }}"
